
name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    uses: ./.github/workflows/pytest.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install & Build Poetry
        run: pip install poetry

      - name: Get project version via poetry
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          TAG_NAME="v${{ steps.get_version.outputs.VERSION }}"
          RELEASE_NAME="meshroom $TAG_NAME"

          gh release delete "$TAG_NAME" -y || true
          gh release create "$TAG_NAME" --title "$RELEASE_NAME" --generate-notes
